kafka:
  compression-codec: zstd
metadata:
  workers: 3
  cacheduration: 30m
  cacherefresh: 1h
  cachecheckinterval: 2m
  providers:
    type: snmp
    pollerretries: 1
    pollertimeout: 1s
    ports:
      ::/0: 161
    agents:
      100.126.16.9: ""
    credentials:
      ::/0:
        communities: public
      # 100.126.16.0/24:
      #   communities: [public]
      100.126.16.0/25:
        # communities: [public]
        username: snmpuser
        authenticationprotocol: SHA
        authenticationpassphrase: "1234567890"
        # privacy-protocol: AES
        # privacy-passphrase: 1234567890
flow:
  inputs:
    - type: udp
      decoder: netflow
      listen: :2055
      workers: 6
      receive-buffer: 20971520
    - type: udp
      decoder: netflow
      listen: :3055
      workers: 6
      receive-buffer: 20971520
    - type: udp
      decoder: sflow
      listen: :6343
      workers: 6
      receive-buffer: 10485760
core:
  workers: 6
  defaultsamplingrate: {}
  overridesamplingrate: 1
  exporter-classifiers:
    # This is an example. This should be customized depending on how
    # your exporters are named.
    - ClassifySiteRegex(Exporter.Name, "^([^-]+)-", "$1")
    - ClassifyRegion("russia")
    - ClassifyTenant("acme")
    - ClassifyRole("edge")
  interface-classifiers:
    - |
      ClassifyConnectivityRegex(Interface.Description, "^(?i)(transit|pni|ppni|ix):? ", "$1") &&
      ClassifyProviderRegex(Interface.Description, "^\\S+?\\s(\\S+)", "$1") &&
      ClassifyExternal()
    - ClassifyInternal()