# If possible, overrides should go there!

# If you prefer to use geo IP databases from host, uncomment this block.

# services:
#   akvorado-orchestrator:
#     volumes:
#       - /usr/share/GeoIP:/usr/share/GeoIP:ro
