name: CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - run: pip install -r requirements.txt
      - run: pytest -q
      - run: go build -o kentavra-go cmd/kentavra/main.go
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/example/kentavra:latest
          provenance: false
          build-args: |
            KENTAVRA_VERSION=${{ github.sha }}
            UI_PORT=8000
        env:
          DOCKER_BUILDKIT: 1
